// Polyfills for NeDB compatibility with newer Node.js versions
const util = require("util");
if (!util.isArray) {
    util.isArray = Array.isArray;
}
if (!util.isDate) {
    util.isDate = (val: any): val is Date => val instanceof Date;
}
if (!util.isRegExp) {
    util.isRegExp = (val: any): val is RegExp => val instanceof RegExp;
}

import * as path from "path";


const Datastore = require("nedb");


// Interface representing a contact record
// _id is optional because it's auto-generated by the database
export interface IContact {
    _id?: number,
    name: string,
    email: string
}


// Worker class that handles all contact database operations using NeDB
export class Worker {

    private db: Nedb;

    // Initialize the NeDB datastore
    // Creates a persistent database file in the dist directory
    constructor() {
        this.db = new Datastore({
            filename: path.join(__dirname, "contacts.db"),
            autoload: true
        });
    }


    // Retrieve all contacts from the database
    public listContacts(): Promise<IContact[]> {

        console.log("Contacts.Worker.listContacts()");

        return new Promise((resolve, reject) => {
            this.db.find(
                {},
                (error: Error | null, inDocs: IContact[]) => {
                    if (error) {
                        console.log("Contacts.Worker.listContacts(): Error", error);
                        reject(error);
                    } else {
                        console.log("Contacts.Worker.listContacts(): Ok", inDocs);
                        resolve(inDocs);
                    }
                }
            );
        });
    }


    // Add a new contact to the database
    public addContact(inContact: IContact): Promise<IContact> {

        console.log("Contacts.Worker.addContact()", inContact);

        return new Promise((resolve, reject) => {
            this.db.insert(
                inContact,
                (error: Error | null, inNewDoc: IContact) => {
                    if (error) {
                        console.log("Contacts.Worker.addContact(): Error", error);
                        reject(error);
                    } else {
                        console.log("Contacts.Worker.addContact(): Ok", inNewDoc);
                        resolve(inNewDoc);
                    }
                }
            );
        });
    }


    // Remove a contact from the database by its _id
    public deleteContact(inID: string): Promise<void> {

        console.log("Contacts.Worker.deleteContact()", inID);

        return new Promise((resolve, reject) => {
            this.db.remove(
                { _id: inID },
                {},
                (error: Error | null, inNumRemoved: number) => {
                    if (error) {
                        console.log("Contacts.Worker.deleteContact(): Error", error);
                        reject(error);
                    } else {
                        console.log("Contacts.Worker.deleteContact(): Ok", inNumRemoved);
                        resolve(undefined);
                    }
                }
            );
        });
    }

    // Update an existing contact's information (Additional Feature)
    // Uses NeDB's update method with returnUpdatedDocs to return the modified record
    public updateContact(inContact: IContact): Promise<IContact> {

        console.log("Contacts.Worker.updateContact()", " - ", inContact.name, ":", inContact.email);

        return new Promise((resolve, reject) => {
            this.db.update(
                { _id: inContact._id },
                inContact,
                { multi: false, upsert: false, returnUpdatedDocs: true },
                (error: Error | null, numAffected: number, affectedDocuments: IContact, upsert: boolean) => {
                    if (error) {
                        console.log("Contacts.Worker.updateContact(): Error", error);
                        reject(error);
                    } else {
                        resolve(affectedDocuments);
                    }
                }
            );
        });
    }
}
